version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

workflows: 
   version: 2
   build-deploy: 
     jobs:
       - build
       - deploy:
           requires:
             - build 
           filters:
             branches:
               only: master 

jobs: 
   build:
     docker: 
       - image: circleci/python:3.6	
     steps:
       - checkout
   
   deploy:
     docker: 
       - image: circleci/python:3.6	 
     steps:
       - checkout
       - run:
           name: Install awscli
           command: sudo pip install awscli
       - aws-s3/sync:
           from: bucket
           to: 's3://beansters-site/html'
           arguments: | 
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true
           aws-access-key-id: AWS_ACCESS_KEY_ID
           aws-region: AWS_REGION
           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
