version: 2.1

orbs:
  aws-s3: circleci/aws-s3@1.0.15

workflows:
   version: 2
   build: 
     jobs:
       - build

jobs: 
   build:
     docker:
       - image: 'cimg/python:3.6'
     steps:
       - checkout
       - aws-s3/sync:
           from: /home/circleci/project
           to: 's3://beansters-site/html'
           arguments: | 
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true
