version: 2

workflows: 
   version: 2
   build-deploy: 
     jobs:
       - build
       - deploy:
           requires:
             - build 
           filters:
             branches:
               only: master 

jobs: 
   build:
     docker: 
       - image: alpine:3.4 
   
   deploy:
     docker: 
       - image: alpine:3.4 
     steps:
       - checkout
       - aws-s3/sync:
           from: bucket
           to: 's3://beansters-site/html'
           arguments: | 
             --acl public-read \
             --cache-control "max-age=86400"
           overwrite: true
           aws-access-key-id: AWS_ACCESS_KEY_ID
           aws-region: AWS_REGION
           aws-secret-access-key: AWS_SECRET_ACCESS_KEY
